import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET() {
  const transactions = await prisma.carbonTransaction.findMany({
    include: { department: true, emissionFactor: true },
    orderBy: { transactionDate: 'desc' },
  });
  return NextResponse.json(transactions);
}

export async function POST(req: NextRequest) {
  const { departmentId, emissionFactorId, sourceModule, quantity, transactionDate } = await req.json();

  if (!departmentId || !emissionFactorId || !sourceModule || quantity === undefined) {
    return NextResponse.json(
      { error: 'departmentId, emissionFactorId, sourceModule, and quantity are required' },
      { status: 400 }
    );
  }

  const factor = await prisma.emissionFactor.findUnique({ where: { id: emissionFactorId } });
  if (!factor) {
    return NextResponse.json({ error: 'Emission factor not found' }, { status: 404 });
  }

  let config = await prisma.eSGConfiguration.findFirst();
  const autoCalc = config?.autoEmissionCalc ?? true;

  const co2Calculated = autoCalc
    ? Number(quantity) * Number(factor.factorValue)
    : Number(quantity);

  const transaction = await prisma.carbonTransaction.create({
    data: {
      departmentId,
      emissionFactorId,
      sourceModule,
      quantity,
      co2Calculated,
      transactionDate: transactionDate ? new Date(transactionDate) : new Date(),
      autoGenerated: autoCalc,
    },
  });

  return NextResponse.json(transaction, { status: 201 });
}
